development:
  sessions:
    default:
      database: cv_dev
      hosts:
        - localhost:27017
  options:
    identity_map_enabled: true
    include_root_in_json: true
    raise_not_found_error: false
    use_utc: true
test:
  sessions:
    default:
      database: cv_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
        
production:
  sessions:
    default:
      database: cv
      hosts:
        - localhost:27017
      options:
        consistency: :strong
  options:
    raise_not_found_error: false
    identity_map_enabled: true
    include_root_in_json: true
    use_utc: true
